from setuptools import setup, find_packages

setup(
    name="aegis-cli",
    version="1.0.0",
    description="Comprehensive cybersecurity toolkit",
    author="Security Professional",
    packages=find_packages(),
    install_requires=[
        "click>=8.0.0",
        "requests>=2.28.0",
        "rich>=13.0.0",
        "python-nmap>=0.7.1",
        "scapy>=2.4.5",
        "cryptography>=38.0.0",
        "pyyaml>=6.0",
        "jinja2>=3.1.0",
        "watchdog>=2.1.0",
        "psutil>=5.9.0",
        "tabulate>=0.9.0",
        "pydantic>=1.10.0",
        "colorama>=0.4.6",
        "tldextract>=3.4.0",
        "dnspython>=2.2.0",
        "httpx>=0.24.0",
        "beautifulsoup4>=4.11.0",
        "lxml>=4.9.0",
    ],
    entry_points={
        "console_scripts": [
            "aegis=aegis.cli:main",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Information Technology",
        "Topic :: Security",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)