import click
import json
from datetime import datetime
from pathlib import Path
from aegis.core import console
from aegis.config import config

class ReportGenerator:
    def __init__(self):
        self.findings = []
        self.report_dir = config.reports_dir
    
    def add_finding(self, module: str, title: str, severity: str, description: str, details: str = ""):
        """Add a finding to the report"""
        self.findings.append({
            'timestamp': datetime.now().isoformat(),
            'module': module,
            'title': title,
            'severity': severity,
            'description': description,
            'details': details
        })
    
    def generate_html(self, title: str = "Security Assessment Report") -> str:
        """Generate HTML report"""
        html_template = """<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        .header {{ background: #2c3e50; color: white; padding: 20px; border-radius: 5px; }}
        .summary {{ background: white; padding: 20px; margin: 20px 0; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
        .finding {{ background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #3498db; border-radius: 3px; }}
        .critical {{ border-left-color: #e74c3c; }}
        .high {{ border-left-color: #e67e22; }}
        .medium {{ border-left-color: #f39c12; }}
        .low {{ border-left-color: #f1c40f; }}
        .info {{ border-left-color: #3498db; }}
        .good {{ border-left-color: #27ae60; }}
        .severity {{ display: inline-block; padding: 3px 8px; border-radius: 3px; color: white; font-size: 12px; font-weight: bold; }}
        .severity.critical {{ background: #e74c3c; }}
        .severity.high {{ background: #e67e22; }}
        .severity.medium {{ background: #f39c12; }}
        .severity.low {{ background: #f1c40f; color: #333; }}
        .severity.info {{ background: #3498db; }}
        .severity.good {{ background: #27ae60; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #34495e; color: white; }}
        tr:hover {{ background: #f5f5f5; }}
        .footer {{ text-align: center; margin-top: 40px; color: #7f8c8d; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p>Generated on: {timestamp}</p>
        <p>Total Findings: {total}</p>
    </div>
    
    <div class="summary">
        <h2>Executive Summary</h2>
        <p>This security assessment report contains <strong>{total}</strong> findings across multiple security domains.</p>
        <table>
            <tr><th>Severity</th><th>Count</th></tr>
            {severity_summary}
        </table>
    </div>
    
    <div class="findings">
        <h2>Detailed Findings</h2>
        {findings_html}
    </div>
    
    <div class="footer">
        <p>Generated by Aegis CLI - Advanced Security Toolkit</p>
    </div>
</body>
</html>"""
        
        # Generate severity summary
        severities = {}
        for f in self.findings:
            sev = f['severity'].lower()
            severities[sev] = severities.get(sev, 0) + 1
        
        severity_rows = ""
        for sev, count in sorted(severities.items()):
            severity_rows += f"<tr><td>{sev.upper()}</td><td>{count}</td></tr>\n"
        
        # Generate findings HTML
        findings_html = ""
        for f in self.findings:
            sev_class = f['severity'].lower()
            findings_html += f"""
            <div class="finding {sev_class}">
                <span class="severity {sev_class}">{f['severity']}</span>
                <h3>[{f['module']}] {f['title']}</h3>
                <p><strong>Description:</strong> {f['description']}</p>
                {f'<p><strong>Details:</strong> {f["details"]}</p>' if f['details'] else ''}
                <p><small>Timestamp: {f['timestamp']}</small></p>
            </div>
            """
        
        return html_template.format(
            title=title,
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            total=len(self.findings),
            severity_summary=severity_rows,
            findings_html=findings_html
        )
    
    def generate_json(self) -> str:
        """Generate JSON report"""
        report = {
            'metadata': {
                'generated_at': datetime.now().isoformat(),
                'tool': 'Aegis CLI',
                'version': '1.0.0',
                'total_findings': len(self.findings)
            },
            'summary': {},
            'findings': self.findings
        }
        
        # Generate severity summary
        for f in self.findings:
            sev = f['severity'].lower()
            report['summary'][sev] = report['summary'].get(sev, 0) + 1
        
        return json.dumps(report, indent=2)
    
    def generate_markdown(self, title: str = "Security Assessment Report") -> str:
        """Generate Markdown report"""
        md = f"""# {title}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Total Findings:** {len(self.findings)}

## Executive Summary

This security assessment identified **{len(self.findings)}** security findings.

### Severity Breakdown

| Severity | Count |
|----------|-------|
"""
        
        # Severity breakdown
        severities = {}
        for f in self.findings:
            sev = f['severity'].lower()
            severities[sev] = severities.get(sev, 0) + 1
        
        for sev, count in sorted(severities.items()):
            md += f"| {sev.upper()} | {count} |\n"
        
        md += "\n## Detailed Findings\n\n"
        
        # Findings
        for f in self.findings:
            md += f"""### [{f['severity']}] {f['title']}

- **Module:** {f['module']}
- **Severity:** {f['severity']}
- **Description:** {f['description']}
{f'- **Details:** {f["details"]}' if f['details'] else ''}
- **Timestamp:** {f['timestamp']}

---

"""
        
        md += "\n*Generated by Aegis CLI - Advanced Security Toolkit*"
        return md

@click.group()
def report_group():
    """Report generation and management"""
    pass

@report_group.command()
@click.option('--format', '-f', 'output_format', default='html',
              type=click.Choice(['html', 'json', 'markdown']),
              help='Report format')
@click.option('--output', '-o', help='Output file path')
@click.option('--title', '-t', default='Security Assessment Report', help='Report title')
def generate(output_format, output, title):
    """Generate security assessment report"""
    generator = ReportGenerator()
    
    # Example findings (in real usage, these would come from scan results)
    generator.add_finding('recon', 'Open Ports Detected', 'Info', 
                         'Port scan identified open ports on target system',
                         'Ports: 80, 443, 22')
    generator.add_finding('vuln', 'Missing Security Headers', 'Medium',
                         'HTTP response missing security headers',
                         'Missing: X-Frame-Options, CSP')
    generator.add_finding('web', 'Weak SSL Configuration', 'High',
                         'Server supports outdated TLS versions',
                         'TLS 1.0 and 1.1 enabled')
    
    # Generate report
    if output_format == 'html':
        content = generator.generate_html(title)
        ext = 'html'
    elif output_format == 'json':
        content = generator.generate_json()
        ext = 'json'
    else:
        content = generator.generate_markdown(title)
        ext = 'md'
    
    # Determine output path
    if not output:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        output = generator.report_dir / f"report_{timestamp}.{ext}"
    
    # Write report
    with open(output, 'w') as f:
        f.write(content)
    
    click.echo(f"[green]✓ Report generated: {output}[/green]")
    click.echo(f"[dim]Format: {output_format.upper()}, Findings: {len(generator.findings)}[/dim]")

@report_group.command()
@click.option('--input', '-i', 'input_file', required=True, help='Input file with findings (JSON)')
@click.option('--format', '-f', 'output_format', default='html',
              type=click.Choice(['html', 'json', 'markdown']))
@click.option('--output', '-o', required=True, help='Output file path')
def convert(input_file, output_format, output):
    """Convert findings to different report format"""
    # Read input
    with open(input_file, 'r') as f:
        data = json.load(f)
    
    generator = ReportGenerator()
    generator.findings = data.get('findings', [])
    
    # Generate in new format
    if output_format == 'html':
        content = generator.generate_html()
    elif output_format == 'json':
        content = generator.generate_json()
    else:
        content = generator.generate_markdown()
    
    with open(output, 'w') as f:
        f.write(content)
    
    click.echo(f"[green]✓ Converted to {output_format.upper()}: {output}[/green]")

@report_group.command()
def list():
    """List generated reports"""
    report_dir = config.reports_dir
    
    if not report_dir.exists():
        click.echo("No reports directory found.")
        return
    
    reports = sorted(report_dir.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True)
    
    if not reports:
        click.echo("No reports found.")
        return
    
    click.echo("\n[cyan]Generated Reports:[/cyan]\n")
    
    for report in reports[:20]:
        stat = report.stat()
        size = stat.st_size
        mtime = datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M')
        
        size_str = f"{size}B" if size < 1024 else f"{size/1024:.1f}KB"
        
        click.echo(f"  {report.name:30} {size_str:>10} {mtime}")

@report_group.command()
@click.option('--report-id', '-r', required=True, help='Report filename to view')
def view(report_id):
    """View a specific report"""
    report_path = config.reports_dir / report_id
    
    if not report_path.exists():
        click.echo(f"[red]Report not found: {report_id}[/red]")
        return
    
    with open(report_path, 'r') as f:
        content = f.read()
    
    # Preview first 50 lines
    lines = content.split('\n')[:50]
    click.echo("\n".join(lines))
    
    if len(content.split('\n')) > 50:
        click.echo("\n[dim]... (truncated, use --full to see complete report)[/dim]")
